// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa3j6W7z1ly-3mRhGFdvtsLkksp3z92gQ',
    appId: '1:213327355200:android:c60e57a0f975b17cda2ea5',
    messagingSenderId: '213327355200',
    projectId: 'mycard-e0c4c',
    storageBucket: 'mycard-e0c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQBaMXUDTlgeqmsptNfUNr0cpAHqVNAq4',
    appId: '1:213327355200:ios:43e844186a11c145da2ea5',
    messagingSenderId: '213327355200',
    projectId: 'mycard-e0c4c',
    storageBucket: 'mycard-e0c4c.appspot.com',
    iosClientId: '213327355200-562c30mh6skr1lvc08p3da36pquntmce.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQBaMXUDTlgeqmsptNfUNr0cpAHqVNAq4',
    appId: '1:213327355200:ios:43e844186a11c145da2ea5',
    messagingSenderId: '213327355200',
    projectId: 'mycard-e0c4c',
    storageBucket: 'mycard-e0c4c.appspot.com',
    iosClientId: '213327355200-562c30mh6skr1lvc08p3da36pquntmce.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
